# Generated by Django 4.2.23 on 2025-07-18 02:38

from django.db import migrations, models
import leave.models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaveapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='year',
            field=models.IntegerField(default=leave.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='current_year_entitlement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
