# Generated by Django 4.2.23 on 2025-07-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leavebalance_year_alter_leavebalance_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='region',
            field=models.CharField(choices=[('HK', 'Hong Kong'), ('CN', 'China Mainland')], default='HK', max_length=2),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='friday_penalty_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='includes_friday_penalty',
            field=models.BooleanField(default=False),
        ),
    ]
