# Generated by Django 4.2.23 on 2025-07-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_employeeprofile_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='includes_friday_penalty',
            new_name='includes_saturday_work',
        ),
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='friday_penalty_days',
            new_name='saturday_work_days',
        ),
    ]
