# Generated by Django 4.2.23 on 2025-07-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_rename_includes_friday_penalty_leaveapplication_includes_saturday_work_and_more'),
    ]

    operations = [
    ]
