# Generated by Django 4.2.5 on 2025-07-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_alter_leaveapplication_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('region', models.CharField(choices=[('HK', 'Hong Kong'), ('CN', 'China')], max_length=2)),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_imported', models.BooleanField(default=True, help_text='True if imported from holidays library, False if manually added')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year', 'date'],
                'unique_together': {('date', 'region')},
            },
        ),
    ]
