# Generated by Django 4.2.5 on 2025-07-21 02:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0009_employeeimportrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialLeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(default=datetime.date.today, help_text='Date for which special leave is requested')),
                ('session', models.CharField(choices=[('AM', 'AM (9:00 - 13:00)'), ('PM', 'PM (13:00 - 18:00)'), ('FULL', 'Full Day (9:00 - 18:00)')], default='FULL', max_length=4)),
                ('reason', models.TextField(default='', help_text='Reason for special leave application')),
                ('urgency', models.CharField(choices=[('low', 'Low - Can wait for approval'), ('normal', 'Normal - Standard processing'), ('high', 'High - Need approval soon'), ('urgent', 'Urgent - Need immediate approval')], default='normal', help_text='Urgency level of this leave request', max_length=10)),
                ('credits_used', models.DecimalField(decimal_places=2, default=0, help_text='Special leave credits used (0.5 for AM/PM, 1.0 for Full Day)', max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16)),
                ('manager_comment', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Detailed reason for rejection if applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Date and time when approved', null=True)),
                ('employee_notified', models.BooleanField(default=False, help_text='Whether employee has been notified of status change')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('auto_withdrawn', models.BooleanField(default=False, help_text='Automatically withdrawn if leave date has passed')),
            ],
            options={
                'ordering': ['-leave_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialLeaveApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('edited', 'Edited'), ('comment_added', 'Comment Added'), ('priority_changed', 'Priority Changed'), ('urgency_changed', 'Urgency Changed')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_status', models.CharField(blank=True, max_length=16)),
                ('new_status', models.CharField(blank=True, max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SpecialLeaveNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('claim_submitted', 'Work Claim Submitted'), ('claim_approved', 'Work Claim Approved'), ('claim_rejected', 'Work Claim Rejected'), ('application_submitted', 'Leave Application Submitted'), ('application_approved', 'Leave Application Approved'), ('application_rejected', 'Leave Application Rejected'), ('application_auto_withdrawn', 'Application Auto-Withdrawn'), ('reminder_approval_needed', 'Approval Reminder'), ('urgent_approval_needed', 'Urgent Approval Needed')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='specialworkclaim',
            options={'ordering': ['-work_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when approved', null=True),
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='credits_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Special leave credits earned (0.5 for AM/PM, 1.0 for Full Day)', max_digits=4),
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Additional details about the work performed'),
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='employee_notified',
            field=models.BooleanField(default=False, help_text='Whether employee has been notified of status change'),
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='event_name',
            field=models.CharField(default='Work Event', help_text='Name of the event or reason for working beyond normal hours', max_length=255),
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Priority level of the work performed', max_length=10),
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Detailed reason for rejection if applicable'),
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='session',
            field=models.CharField(choices=[('AM', 'AM (9:00 - 13:00)'), ('PM', 'PM (13:00 - 18:00)'), ('FULL', 'Full Day (9:00 - 18:00)')], default='FULL', max_length=4),
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='work_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when extra work was performed'),
        ),
        migrations.AlterUniqueTogether(
            name='specialworkclaim',
            unique_together={('employee', 'work_date', 'session')},
        ),
        migrations.AddIndex(
            model_name='specialworkclaim',
            index=models.Index(fields=['status', 'work_date'], name='leave_speci_status_fa3622_idx'),
        ),
        migrations.AddIndex(
            model_name='specialworkclaim',
            index=models.Index(fields=['employee', 'status'], name='leave_speci_employe_e266d2_idx'),
        ),
        migrations.AddIndex(
            model_name='specialworkclaim',
            index=models.Index(fields=['priority', 'created_at'], name='leave_speci_priorit_b43da4_idx'),
        ),
        migrations.AddField(
            model_name='specialleavenotification',
            name='leave_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.specialleaveapplication'),
        ),
        migrations.AddField(
            model_name='specialleavenotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_leave_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialleavenotification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_special_leave_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialleavenotification',
            name='work_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.specialworkclaim'),
        ),
        migrations.AddField(
            model_name='specialleaveapprovalworkflow',
            name='leave_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='leave.specialleaveapplication'),
        ),
        migrations.AddField(
            model_name='specialleaveapprovalworkflow',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialleaveapprovalworkflow',
            name='work_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='leave.specialworkclaim'),
        ),
        migrations.AddField(
            model_name='specialleaveapplication',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_special_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialleaveapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.employeeprofile'),
        ),
        migrations.RemoveField(
            model_name='specialworkclaim',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='specialworkclaim',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='specialworkclaim',
            name='days_claimed',
        ),
        migrations.RemoveField(
            model_name='specialworkclaim',
            name='name_of_event',
        ),
        migrations.AddIndex(
            model_name='specialleavenotification',
            index=models.Index(fields=['recipient', 'is_read'], name='leave_speci_recipie_0bfed8_idx'),
        ),
        migrations.AddIndex(
            model_name='specialleavenotification',
            index=models.Index(fields=['notification_type', 'created_at'], name='leave_speci_notific_dd86df_idx'),
        ),
        migrations.AddIndex(
            model_name='specialleaveapprovalworkflow',
            index=models.Index(fields=['timestamp'], name='leave_speci_timesta_37a52e_idx'),
        ),
        migrations.AddIndex(
            model_name='specialleaveapprovalworkflow',
            index=models.Index(fields=['action', 'timestamp'], name='leave_speci_action_80a76b_idx'),
        ),
        migrations.AddIndex(
            model_name='specialleaveapplication',
            index=models.Index(fields=['status', 'leave_date'], name='leave_speci_status_57b17b_idx'),
        ),
        migrations.AddIndex(
            model_name='specialleaveapplication',
            index=models.Index(fields=['employee', 'status'], name='leave_speci_employe_edb67a_idx'),
        ),
        migrations.AddIndex(
            model_name='specialleaveapplication',
            index=models.Index(fields=['urgency', 'created_at'], name='leave_speci_urgency_81b188_idx'),
        ),
        migrations.AddIndex(
            model_name='specialleaveapplication',
            index=models.Index(fields=['leave_date', 'status'], name='leave_speci_leave_d_660618_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specialleaveapplication',
            unique_together={('employee', 'leave_date', 'session')},
        ),
    ]
