# Generated by Django 4.2.5 on 2025-07-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_specialleaveapplication_specialleaveapprovalworkflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialleaveapplication',
            name='leave_end_date',
            field=models.DateField(blank=True, help_text='End date for consecutive leave days (leave blank for single day)', null=True),
        ),
        migrations.AddField(
            model_name='specialworkclaim',
            name='work_end_date',
            field=models.DateField(blank=True, help_text='End date for consecutive work days (leave blank for single day)', null=True),
        ),
        migrations.AlterField(
            model_name='specialleaveapplication',
            name='leave_date',
            field=models.DateField(help_text='Start date for which special leave is requested'),
        ),
        migrations.AlterField(
            model_name='specialleaveapplication',
            name='reason',
            field=models.TextField(help_text='Reason for special leave application'),
        ),
        migrations.AlterField(
            model_name='specialworkclaim',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the work performed'),
        ),
        migrations.AlterField(
            model_name='specialworkclaim',
            name='event_name',
            field=models.CharField(help_text='Name of the event or reason for working beyond normal hours', max_length=255),
        ),
        migrations.AlterField(
            model_name='specialworkclaim',
            name='work_date',
            field=models.DateField(help_text='Start date when extra work was performed'),
        ),
    ]
