# Generated by Django 4.2.5 on 2025-07-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_add_date_range_support'),
    ]

    operations = [
        # Drop tables that no longer exist in models
        migrations.RunSQL(
            "DROP TABLE IF EXISTS leave_specialleaveapplication;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS leave_specialleaveapprovalworkflow;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS leave_specialleavenotification;",
            reverse_sql="",
        ),
    ]
