# Generated by Django 4.2.16 on 2025-07-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0012_auto_20250721_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="company",
            field=models.CharField(
                choices=[
                    ("Krystal Institute Ltd", "Krystal Institute Ltd"),
                    ("Krystal Technology Ltd", "Krystal Technology Ltd"),
                    ("Other", "Other"),
                ],
                default="Krystal Institute Ltd",
                max_length=100,
            ),
        ),
    ]
